const lista = document.querySelector('div#itens')
// console.log(lista.parentNode)
// console.log(lista.childNodes)
// console.log(lista.firstChild)
// console.log(lista.lastChild)
// console.log(lista.nextSibling.nextSibling)
// console.log(lista.previousSibling.previousSibling)
// console.log(lista.children)
console.log(lista.firstElementChild)
console.log(lista.lastElementChild)
console.log(lista.nextElementSibling)
console.log(lista.previousElementSibling)